apiVersion: demo.example.com/v1
kind: DemoApp
metadata:
  labels:
    app.kubernetes.io/name: operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: demoapp-sample
spec:
  # TODO(user): Add fields here
  replicas: 2
